version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - postgresData:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=saptable
      - POSTGRES_USER=rootUser
      - POSTGRES_PASSWORD=rootPassword

  svc:
    build: .
    # user: 1000:1000
    command: bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/workarea
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=saptable
      - POSTGRES_USER=rootUser
      - POSTGRES_PASSWORD=rootPassword
    # depends_on:
    #   - db
  ui:
    # restart: always
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/workarea/frontend
      - ./frontend/node_modules
    command: npm start
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    # depends_on:
    # - svc

volumes:
  postgresData:
# networks:
#   db-net:
#     driver: bridge
